# packages/mcp-toolbox/docker-compose.yml
version: "3.8"

services:
  mcp-toolbox:
    build:
      context: ../../
      dockerfile: mcp-toolbox.Dockerfile
    ports:
      - "${PORT:-11990}:${PORT:-11990}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-11990}
      - DB_PATH=/app/data/packages.db
      - PROXY_ID=${PROXY_ID:-}
      - MCP_SERVER_HOST=${MCP_SERVER_HOST:-host.docker.internal:6050}
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
