version: '3.8'

services:
  server:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - DB_PATH=/app/data/packages.db
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped