name: Publish Packages to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/npm-publish.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find changed packages
        id: changed-packages
        run: |
          # Get all packages
          PACKAGES=$(find packages -type f -name "package.json" -not -path "*/node_modules/*" | grep -o 'packages/[^/]*' | sort | uniq)
          
          # Get last successful run commit
          git fetch origin
          LAST_COMMIT=$(git rev-parse HEAD^)
          
          # Initialize array for changed packages
          CHANGED=()
          
          # Check each package
          for PKG in $PACKAGES; do
            if git diff --name-only $LAST_COMMIT HEAD | grep -q "^$PKG/"; then
              echo "$PKG has changes"
              PKG_NAME=$(basename $PKG)
              CHANGED+=("$PKG_NAME")
            fi
          done
          
          # Convert to JSON array for matrix directly using jq
          if [ ${#CHANGED[@]} -eq 0 ]; then
            echo "No changes detected in any package"
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            JSON_ARRAY=$(printf '%s\n' "${CHANGED[@]}" | jq -R . | jq -c -s .)
            echo "Changed packages: $JSON_ARRAY"
            echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT
          fi

      - name: Set matrix
        id: set-matrix
        run: |
          if [ "${{ steps.changed-packages.outputs.matrix }}" = "[]" ] || [ -z "${{ steps.changed-packages.outputs.matrix }}" ]; then
            echo "No changes detected in any package"
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            echo "matrix=${{ steps.changed-packages.outputs.matrix }}" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: |
          cd packages/${{ matrix.package }}
          yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/${{ matrix.package }}
          # Check if .releaserc.json exists, create if not
          if [ ! -f .releaserc.json ]; then
            echo "Creating .releaserc.json from template"
            cp ../../.github/release-template.json .releaserc.json
          fi
          # Install semantic-release if not in package.json
          if ! grep -q "semantic-release" package.json; then
            yarn add --dev semantic-release @semantic-release/git
          fi
          npx semantic-release 